#  GENERATED by openroad/scripts/waferspace_collateral.py -- do not edit.
#
#  One Metal5 strap of the core grid per supply stub of GRADIENT_NAV2_V3.
#  See that script for why they are here and why they are not a pitch.
#  Macro at (442.0, 1702.01) FS; core y0 = 442.0.

#  --- VDD ------------------------------------------------------------
#  stub y 2002.275 .. 2012.275 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VDD \
    -width 9.5 \
    -offset 1565.275 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  stub y 1882.315 .. 1892.315 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VDD \
    -width 9.5 \
    -offset 1445.315 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  stub y 1795.100 .. 1805.050 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VDD \
    -width 9.45 \
    -offset 1358.075 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  VDD: 3 straps, 28.45 um of Metal5 -> 42.7 mA against the 31 mA the block is sized for.

#  --- VSS ------------------------------------------------------------
#  stub y 2067.685 .. 2077.685 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VSS \
    -width 9.5 \
    -offset 1630.685 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  stub y 1942.355 .. 1951.845 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VSS \
    -width 8.99 \
    -offset 1505.1 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  stub y 1838.495 .. 1848.285 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VSS \
    -width 9.29 \
    -offset 1401.39 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  stub y 1751.700 .. 1761.490 absolute
add_pdn_stripe \
    -grid stdcell_grid \
    -layer Metal5 \
    -nets VSS \
    -width 9.29 \
    -offset 1314.595 \
    -number_of_straps 1 \
    -extend_to_core_ring

#  VSS: 4 straps, 37.07 um of Metal5 -> 55.6 mA against the 31 mA the block is sized for.
