#!/usr/bin/env python3
"""SUPERSEDED -- kept only so the history is legible. Do not run it.

    Use instead:  make lvs-ref T=B26_A TOP_OUT=out_integration

This existed for one day, while `B26_A` had no schematic of its own and its LVS
reference had to be faked by renaming the block's. `XSCHEM/B26_A.sch` now exists
-- the block plus its eleven io_secondary_5p0 clamps -- so the reference comes
out of xschem through `lvs_reference.py`, like every other cell's. Renaming a
netlist to stand in for a different circuit is exactly how an LVS is made to
agree with something that is not what will be fabricated.

--- what it used to say ---

Reference netlist of the INTEGRATED area, for the external LVS.

    python3 scripts/lvs_reference_integration.py   # -> out_integration/B26_A_lvs.spice

`B26_A` is the padring's user area: our `GRADIENT_NAV2` macro, the routing out
to the ring's pins and the tie-offs that program the six digital pads. There is
no schematic of it -- `scripts/integrate_padframe.py` derives it -- so its
reference is the block's own flat reference with the top cell renamed.

That is the whole circuit, and it is legitimate: the tie-offs add no devices.
`assign ZN_OE = VDD` in `verilog/B26_A.v` is a wire, so in the layout the pin
`ZN_OE` is simply another label on the VDD net, and 42 more control pins are
labels on VSS. A SPICE port list cannot say "these 44 names are one node", so
the reference declares the 19 electrical nodes and lets the extraction bring
the extra labels along.

WHAT THIS DOES NOT COVER, and `scripts/check_integration.py` does: that every
one of the 73 pins actually reaches the net it is supposed to. An open tie-off
just leaves a label unused, and LVS run with `--top_lvl_pins` does not fail on
that.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOQUE = ROOT / "out_v2_GRADIENT_NAV2" / "GRADIENT_NAV2_lvs.spice"
CELDA_BLOQUE = "GRADIENT_NAV2"
CELDA = "B26_A"
DESTINO = ROOT / "out_integration" / f"{CELDA}_lvs.spice"


def main() -> int:
    if not BLOQUE.exists():
        sys.exit(f"the block reference is missing: {BLOQUE}\n"
                 f"  run `make lvs-ref T={CELDA_BLOQUE} V=v2` first")

    txt = BLOQUE.read_text()
    nuevo, n = re.subn(rf"^(\.(?:subckt|ends)) +{CELDA_BLOQUE}\b",
                       rf"\1 {CELDA}", txt, flags=re.M)
    #  `.ends` may carry no name at all, so one or two hits are both fine --
    #  zero is not, and that is what this catches.
    if n == 0:
        sys.exit(f"'{CELDA_BLOQUE}' is not declared in {BLOQUE.name}; "
                 f"did the flattening change?")

    cabecera = (
        f"* Reference netlist of {CELDA}: the padring's user area.\n"
        f"* GENERATED by scripts/lvs_reference_integration.py -- do not edit.\n"
        f"* Source: {BLOQUE.relative_to(ROOT)}, with the top cell renamed.\n"
        f"* The tie-offs of verilog/{CELDA}.v add no devices: they only put\n"
        f"* more labels on VDD and VSS. See that script's docstring.\n")
    DESTINO.parent.mkdir(parents=True, exist_ok=True)
    DESTINO.write_text(cabecera + nuevo)

    linea = next(l for l in nuevo.splitlines() if l.lower().startswith(".subckt"))
    print(f"  {DESTINO}")
    print(f"  {linea.split()[1]}: {len(linea.split()) - 2} ports, "
          f"{sum(1 for l in nuevo.splitlines() if l[:1] in 'MmXxCcRrDdQq')} devices")
    return 0


if __name__ == "__main__":
    sys.exit(main())
